# Generated by Django 5.2.5 on 2025-10-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0002_alter_progresstrackers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Career', 'Career'), ('Personal Development', 'Personal Development'), ('Finance', 'Finance'), ('Relationships', 'Relationships'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='goals',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=50),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='mood_rating',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], max_length=1),
        ),
    ]
